/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
    robots: {
        /**
         * Velocity as a double
         */
        velocity: number;
        samples: {
            /**
             * Timestamp in milliseconds
             */
            timestamp: number;
            /**
             * Alliance as an integer
             */
            alliance: number;
            /**
             * Tx value as a double
             */
            tx: number;
            /**
             * Ty value as a double
             */
            ty: number;
            /**
             * Distance as a double
             */
            distance: number;
            [k: string]: unknown;
        }[];
        [k: string]: unknown;
    }[];
    [k: string]: unknown;
}
